/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available courses
         * @description Returns courses that have not ended, ordered by start time ascending. Courses that have been archived or do not have a currently active price are not returned.
         */
        get: operations["listCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a course
         * @description Returns a course that has not been archived and has a currently active price. Unlike `listCourses`, ended courses are still returned.
         */
        get: operations["getCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: uuid
         * @description Public identifier of the course.
         * @example 123e4567-e89b-12d3-a456-426614174000
         */
        CourseId: string;
        ListCoursesResponse: {
            courses: components["schemas"]["Course"][];
        };
        Course: {
            id: components["schemas"]["CourseId"];
            /**
             * @description Public name of the course.
             * @example React Fundamentals
             */
            name: string;
            /**
             * @description Public description of the course.
             * @example Learn the fundamentals of React.
             */
            description: string;
            /**
             * Format: int32
             * @description Number of users currently enrolled in the course.
             * @example 12
             */
            enrollmentCount: number;
            price: components["schemas"]["Price"];
            schedule: components["schemas"]["CourseSchedule"];
        };
        Price: {
            /**
             * Format: int64
             * @description Price in the smallest unit of the currency. For USD, 9900 represents $99.00.
             * @example 9900
             */
            amount: number;
            /**
             * @description ISO 4217 currency code.
             * @example USD
             */
            currency: string;
        };
        CourseSchedule: {
            /**
             * Format: date-time
             * @description Course start time as an RFC 3339 date-time including its UTC offset.
             * @example 2026-10-01T18:00:00-04:00
             */
            startTime: string;
            /**
             * Format: date-time
             * @description Course end time as an RFC 3339 date-time including its UTC offset. Always after `startTime`.
             * @example 2026-10-01T20:00:00-04:00
             */
            endTime: string;
            /**
             * @description IANA time zone identifier the course is held in. Use this, rather than the UTC offset in `startTime` and `endTime`, to display local times correctly across daylight saving changes.
             * @example America/New_York
             */
            timeZone: string;
        };
        /** @description Error response in the RFC 9457 Problem Details format. Clients should branch on `code`, not on `title` or `detail`. New codes may be added in future versions; clients should treat an unrecognized `code` as a generic error for the response's HTTP status. */
        ProblemDetails: {
            /**
             * @description Short, human-readable summary of the problem.
             * @example Course not found
             */
            title: string;
            /** @description Human-readable explanation specific to this occurrence. */
            detail: string;
            /**
             * @description Stable machine-readable error code.
             * @example COURSE_NOT_FOUND
             */
            code: string;
        };
    };
    responses: {
        /** @description The course identifier is malformed. */
        InvalidCourseId: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Course not found, archived, or does not have a currently active price. */
        CourseNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Internal server error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Public identifier of the course. */
        CourseId: components["schemas"]["CourseId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved available courses. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCoursesResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public identifier of the course. */
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved the course. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            400: components["responses"]["InvalidCourseId"];
            404: components["responses"]["CourseNotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
