/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available courses
         * @description Returns courses that have not ended, ordered by start time ascending. Courses that have been archived or do not have an effective price are not returned.
         */
        get: operations["listCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a course
         * @description Returns a course that has not been archived and has an effective price. Unlike `listCourses`, ended courses are still returned. An unknown or malformed identifier results in a 404.
         */
        get: operations["getCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ListCoursesResponse: {
            courses: components["schemas"]["Course"][];
        };
        Course: {
            /**
             * @description Public identifier of the course.
             * @example crs_01HZX3
             */
            id: string;
            /**
             * @description Public name of the course.
             * @example React Fundamentals
             */
            name: string;
            /**
             * @description Public description of the course.
             * @example Learn the fundamentals of React.
             */
            description: string;
            /**
             * Format: int32
             * @description Number of users currently enrolled in the course.
             * @example 12
             */
            enrollmentCount: number;
            price: components["schemas"]["Price"];
            schedule: components["schemas"]["CourseSchedule"];
        };
        GetCourseResponse: components["schemas"]["Course"];
        Price: {
            /**
             * Format: int64
             * @description Price in the smallest unit of the currency. For USD, 9900 represents $99.00.
             * @example 9900
             */
            amount: number;
            /**
             * @description ISO 4217 currency code.
             * @example USD
             */
            currency: string;
        };
        CourseSchedule: {
            /**
             * Format: date-time
             * @description Course start time as an RFC 3339 date-time including its UTC offset.
             * @example 2026-10-01T18:00:00-04:00
             */
            startTime: string;
            /**
             * Format: date-time
             * @description Course end time as an RFC 3339 date-time including its UTC offset. Always after `startTime`.
             * @example 2026-10-01T20:00:00-04:00
             */
            endTime: string;
            /**
             * @description IANA time zone identifier the course is held in. Use this, rather than the UTC offset in `startTime` and `endTime`, to display local times correctly across daylight saving changes.
             * @example America/New_York
             */
            timeZone: string;
        };
        ErrorResponse: {
            /** @description Human-readable description of the error. */
            message: string;
            /**
             * @description Stable machine-readable error code. Clients should branch on this rather than on message.
             * @enum {string}
             */
            code: "COURSE_NOT_FOUND" | "INTERNAL_SERVER_ERROR";
        };
    };
    responses: {
        /** @description Course not found, archived, or does not have an effective price. */
        CourseNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Public identifier of the course. */
        CourseId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved available courses. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCoursesResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Public identifier of the course. */
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved the course. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCourseResponse"];
                };
            };
            404: components["responses"]["CourseNotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
