/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available courses
         * @description Returns courses that have not ended, ordered by start time ascending. Courses that have been archived are not returned.
         */
        get: operations["listCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ListCoursesResponse: {
            courses: components["schemas"]["Course"][];
        };
        Course: {
            /**
             * @description Public name of the course.
             * @example React Fundamentals
             */
            name: string;
            /**
             * @description Public description of the course.
             * @example Learn the fundamentals of React.
             */
            description: string;
            /**
             * Format: int32
             * @description Number of users currently enrolled in the course.
             * @example 12
             */
            enrollmentCount: number;
            price: components["schemas"]["Price"];
            schedule: components["schemas"]["CourseSchedule"];
        };
        Price: {
            /**
             * Format: int64
             * @description Price in the smallest unit of the currency. For USD, 9900 represents $99.00.
             * @example 9900
             */
            amount: number;
            /**
             * @description ISO 4217 currency code.
             * @example USD
             */
            currency: string;
        };
        CourseSchedule: {
            /**
             * Format: date-time
             * @description Course start time as an RFC 3339 date-time including its UTC offset.
             * @example 2026-10-01T18:00:00-04:00
             */
            startTime: string;
            /**
             * Format: date-time
             * @description Course end time as an RFC 3339 date-time including its UTC offset.
             * @example 2026-10-01T20:00:00-04:00
             */
            endTime: string;
            /**
             * @description IANA time zone identifier.
             * @example America/New_York
             */
            timeZone: string;
        };
        ErrorResponse: {
            /**
             * Format: int32
             * @description HTTP status code.
             * @example 500
             */
            statusCode: number;
            /**
             * @description Human-readable description of the error.
             * @example Internal server error
             */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved available courses. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCoursesResponse"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
