services:
  postgres-test:
    image: postgres:17
    environment:
      POSTGRES_USER: course_app_test
      POSTGRES_PASSWORD: course_app_test
      POSTGRES_DB: course_app_test
    ports:
      - "5433:5432"
